<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="4" errors="1" failures="1" skip="1"><testcase classname="tests_locatable.test_locatable" name="test_succeeding" time="0.000"></testcase><testcase classname="tests_locatable.test_locatable" name="test_failing" time="0.001"><failure type="exceptions.AssertionError" message=""><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/wenns/src/wenns/sonar-python/sonar-python-plugin/src/test/resources/org/sonar/plugins/python/smoketest_project_3/tests_locatable/test_locatable.py", line 5, in test_failing
    assert False
AssertionError
]]></failure></testcase><testcase classname="tests_locatable.test_locatable" name="test_crashing" time="0.005"><error type="exceptions.RuntimeError" message=""><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/wenns/src/wenns/sonar-python/sonar-python-plugin/src/test/resources/org/sonar/plugins/python/smoketest_project_3/tests_locatable/test_locatable.py", line 8, in test_crashing
    raise RuntimeError()
RuntimeError
]]></error></testcase><testcase classname="tests_locatable.test_locatable" name="test_skipped" time="0.001"><skipped type="unittest.case.SkipTest" message=""><![CDATA[SkipTest
]]></skipped></testcase></testsuite>